/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicPresenceImageNameRouteImport } from './routes/api/public/presence-image.$name'
import { Route as ApiPublicPresenceSwatchColorRouteImport } from './routes/api/public/presence-swatch.$color'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'
import { Route as ApiPublicWorkerPollRouteImport } from './routes/api/public/worker/poll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPresenceImageNameRoute =
  ApiPublicPresenceImageNameRouteImport.update({
    id: '/api/public/presence-image/$name',
    path: '/api/public/presence-image/$name',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPresenceSwatchColorRoute =
  ApiPublicPresenceSwatchColorRouteImport.update({
    id: '/api/public/presence-swatch/$color',
    path: '/api/public/presence-swatch/$color',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerPollRoute = ApiPublicWorkerPollRouteImport.update({
  id: '/api/public/worker/poll',
  path: '/api/public/worker/poll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/presence-image/$name': typeof ApiPublicPresenceImageNameRoute
  '/api/public/presence-swatch/$color': typeof ApiPublicPresenceSwatchColorRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/presence-image/$name': typeof ApiPublicPresenceImageNameRoute
  '/api/public/presence-swatch/$color': typeof ApiPublicPresenceSwatchColorRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/presence-image/$name': typeof ApiPublicPresenceImageNameRoute
  '/api/public/presence-swatch/$color': typeof ApiPublicPresenceSwatchColorRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/poll': typeof ApiPublicWorkerPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/discord/callback'
    | '/api/public/presence-image/$name'
    | '/api/public/presence-swatch/$color'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/discord/callback'
    | '/api/public/presence-image/$name'
    | '/api/public/presence-swatch/$color'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/poll'
  id:
    | '__root__'
    | '/'
    | '/api/public/discord/callback'
    | '/api/public/presence-image/$name'
    | '/api/public/presence-swatch/$color'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicPresenceImageNameRoute: typeof ApiPublicPresenceImageNameRoute
  ApiPublicPresenceSwatchColorRoute: typeof ApiPublicPresenceSwatchColorRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerPollRoute: typeof ApiPublicWorkerPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presence-image/$name': {
      id: '/api/public/presence-image/$name'
      path: '/api/public/presence-image/$name'
      fullPath: '/api/public/presence-image/$name'
      preLoaderRoute: typeof ApiPublicPresenceImageNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presence-swatch/$color': {
      id: '/api/public/presence-swatch/$color'
      path: '/api/public/presence-swatch/$color'
      fullPath: '/api/public/presence-swatch/$color'
      preLoaderRoute: typeof ApiPublicPresenceSwatchColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/poll': {
      id: '/api/public/worker/poll'
      path: '/api/public/worker/poll'
      fullPath: '/api/public/worker/poll'
      preLoaderRoute: typeof ApiPublicWorkerPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicPresenceImageNameRoute: ApiPublicPresenceImageNameRoute,
  ApiPublicPresenceSwatchColorRoute: ApiPublicPresenceSwatchColorRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerPollRoute: ApiPublicWorkerPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
